const testUsers = [
  {
    email: "user1@test.com",
    name: "Liberal Sarah",
    city: "Palm Beach",
    state: "FL",
    latitude: 26.7056,
    longitude: -80.0364,
    politicalBeliefs: ["Liberal"],
    religion: "Christian",
    lifeStage: ["Married", "Working Professional"],
  },
  {
    email: "user2@test.com",
    name: "Conservative Mike",
    city: "Miami",
    state: "FL",
    latitude: 25.7617,
    longitude: -80.1918,
    politicalBeliefs: ["Conservative"],
    religion: "Catholic",
    lifeStage: ["Single", "Entrepreneur"],
  },
  {
    email: "user3@test.com",
    name: "Moderate Jane",
    city: "Orlando",
    state: "FL",
    latitude: 28.5383,
    longitude: -81.3792,
    politicalBeliefs: ["Moderate"],
    religion: "Agnostic",
    lifeStage: ["Divorced", "Single Parent"],
  },
  {
    email: "user4@test.com",
    name: "Progressive Alex",
    city: "Atlanta",
    state: "GA",
    latitude: 33.7490,
    longitude: -84.3880,
    politicalBeliefs: ["Progressive"],
    religion: "Jewish",
    lifeStage: ["Married", "Have Children"],
  },
  {
    email: "user5@test.com",
    name: "Independent Chris",
    city: "New York",
    state: "NY",
    latitude: 40.7128,
    longitude: -74.0060,
    politicalBeliefs: ["Independent"],
    religion: "Atheist",
    lifeStage: ["Single", "Career Focused"],
  },
];